# Generated by Django 3.2.12 on 2022-03-01 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hit_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
