# Generated by Django 4.0.1 on 2022-03-01 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_hitcount_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitcount',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
